In [1]:
import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import GCNConv

# Define a simple graph with 4 nodes
edge_index = torch.tensor(
    [
        [0, 1, 1, 2, 2, 3],  # From
        [1, 0, 2, 1, 3, 2],  # To
    ],
    dtype=torch.long,
)  # Each pair represents an edge

# Features for each node (random for simplicity)
x = torch.rand((4, 3))  # 4 nodes, each with a 3-dimensional feature

# Create a PyTorch Geometric graph object
graph = Data(x=x, edge_index=edge_index)

print(graph)

Data(x=[4, 3], edge_index=[2, 6])


In [4]:
import torch.nn as nn


class SimpleGNN(nn.Module):
    def __init__(self, in_features, hidden_dim, out_features):
        super().__init__()
        self.conv1 = GCNConv(in_features, hidden_dim)  # First graph conv layer
        self.conv2 = GCNConv(hidden_dim, out_features)  # Second graph conv layer

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)  # Message passing step 1
        x = F.relu(x)  # Apply activation function
        x = self.conv2(x, edge_index)  # Message passing step 2
        return x


# Create the model
model = SimpleGNN(in_features=3, hidden_dim=5, out_features=2)

# Forward pass (Get node representations)
output = model(graph.x, graph.edge_index)
print(output)

tensor([[-1.2258, -1.0119],
        [-1.4147, -1.2552],
        [-1.4661, -1.4053],
        [-1.1372, -1.1744]], grad_fn=<AddBackward0>)


In [8]:
print(model)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)
Parameter containing:
tensor([[-0.3588,  0.5035, -0.8183],
        [ 0.8264, -0.0808, -0.7439],
        [ 0.6600, -0.2381,  0.3530],
        [-0.1486, -0.6463, -0.0533],
        [ 0.7522,  0.7557,  0.7340]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)
Parameter containing:
tensor([[-0.3809,  0.7348, -0.7144,  0.9006, -0.9067],
        [-0.5737,  0.0233, -0.9088, -0.2318, -0.6454]], requires_grad=True)
